AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  lambdajavalabfunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.java.lab.controller.LambdaController
      Runtime: java11
      CodeUri: './code/'
      MemorySize: 512
      Timeout: 30